// Implementation file for parser generated by fsyacc
module GeneratedParser.Yacc
#nowarn "64";; // turn off warnings that type variables used in production annotations are instantiated to concrete type
open Microsoft.FSharp.Text.Lexing
open Microsoft.FSharp.Text.Parsing.ParseHelpers
# 1 "asdf.fsy"


open Test3.Parser
open Test3.Parser.Ast
open Test3.Lexer
open Test3.Parser
open Microsoft.FSharp.Quotations
open Microsoft.FSharp.Quotations.Patterns
open Microsoft.FSharp.Compiler
open Microsoft.FSharp.Compiler.Reflection


# 19 "asdf.fs"
// This type is the type of tokens accepted by the parser
open Test3.Lexer
type tokenId = 
    | TOKEN_LocalVar
    | TOKEN_Ident
    | TOKEN_GlobalVar
    | TOKEN_Rparen
    | TOKEN_Lparen
    | TOKEN_Kw_from
    | TOKEN_Kw_select
    | TOKEN_end_of_input
    | TOKEN_error
// This type is used to give symbolic names to token indexes, useful for error messages
type nonTerminalId = 
    | NONTERM__startSqlExpression
    | NONTERM_SqlExpression
    | NONTERM_yard_exp_brackets_1
    | NONTERM_yard_exp_brackets_2
    | NONTERM_yard_exp_brackets_3
    | NONTERM_yard_exp_brackets_4

// This function maps tokens to integers indexes
let tagOfToken (t:token) = 
  match t with
  | LocalVar _ -> 0 
  | Ident _ -> 1 
  | GlobalVar _ -> 2 
  | Rparen _ -> 3 
  | Lparen _ -> 4 
  | Kw_from _ -> 5 
  | Kw_select _ -> 6 

// This function maps integers indexes to symbolic token ids
let tokenTagToTokenId (tokenIdx:int) = 
  match tokenIdx with
  | 0 -> TOKEN_LocalVar 
  | 1 -> TOKEN_Ident 
  | 2 -> TOKEN_GlobalVar 
  | 3 -> TOKEN_Rparen 
  | 4 -> TOKEN_Lparen 
  | 5 -> TOKEN_Kw_from 
  | 6 -> TOKEN_Kw_select 
  | 9 -> TOKEN_end_of_input
  | 7 -> TOKEN_error
  | _ -> failwith "tokenTagToTokenId: bad token"

/// This function maps production indexes returned in syntax errors to strings representing the non terminal that would be produced by that production
let prodIdxToNonTerminal (prodIdx:int) = 
  match prodIdx with
    | 0 -> NONTERM__startSqlExpression 
    | 1 -> NONTERM_SqlExpression 
    | 2 -> NONTERM_SqlExpression 
    | 3 -> NONTERM_SqlExpression 
    | 4 -> NONTERM_SqlExpression 
    | 5 -> NONTERM_SqlExpression 
    | 6 -> NONTERM_yard_exp_brackets_1 
    | 7 -> NONTERM_yard_exp_brackets_2 
    | 8 -> NONTERM_yard_exp_brackets_3 
    | 9 -> NONTERM_yard_exp_brackets_4 
    | _ -> failwith "prodIdxToNonTerminal: bad production index"

let _fsyacc_endOfInputTag = 9 
let _fsyacc_tagOfErrorTerminal = 7

// This function gets the name of a token as a string
let token_to_string (t:token) = 
  match t with 
  | LocalVar _ -> "LocalVar" 
  | Ident _ -> "Ident" 
  | GlobalVar _ -> "GlobalVar" 
  | Rparen _ -> "Rparen" 
  | Lparen _ -> "Lparen" 
  | Kw_from _ -> "Kw_from" 
  | Kw_select _ -> "Kw_select" 

// This function gets the data carried by a token as an object
let _fsyacc_dataOfToken (t:token) = 
  match t with 
  | LocalVar _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | Ident _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | GlobalVar _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | Rparen _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | Lparen _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | Kw_from _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
  | Kw_select _fsyacc_x -> Microsoft.FSharp.Core.Operators.box _fsyacc_x 
let _fsyacc_gotos = [| 0us; 65535us; 3us; 65535us; 0us; 1us; 8us; 9us; 14us; 15us; 3us; 65535us; 0us; 5us; 8us; 5us; 14us; 5us; 3us; 65535us; 0us; 7us; 8us; 7us; 14us; 7us; 3us; 65535us; 0us; 10us; 8us; 10us; 14us; 10us; 3us; 65535us; 0us; 12us; 8us; 12us; 14us; 12us; |]
let _fsyacc_sparseGotoTableRowOffsets = [|0us; 1us; 5us; 9us; 13us; 17us; |]
let _fsyacc_stateToProdIdxsTableElements = [| 1us; 0us; 1us; 0us; 1us; 1us; 1us; 2us; 1us; 3us; 1us; 4us; 1us; 4us; 1us; 5us; 1us; 6us; 1us; 6us; 1us; 7us; 1us; 7us; 1us; 8us; 1us; 8us; 1us; 9us; 1us; 9us; |]
let _fsyacc_stateToProdIdxsTableRowOffsets = [|0us; 2us; 4us; 6us; 8us; 10us; 12us; 14us; 16us; 18us; 20us; 22us; 24us; 26us; 28us; 30us; |]
let _fsyacc_action_rows = 16
let _fsyacc_actionTableElements = [|5us; 32768us; 0us; 2us; 1us; 3us; 2us; 4us; 4us; 8us; 6us; 14us; 0us; 49152us; 0us; 16385us; 0us; 16386us; 0us; 16387us; 1us; 32768us; 3us; 6us; 0us; 16388us; 0us; 16389us; 5us; 32768us; 0us; 2us; 1us; 3us; 2us; 4us; 4us; 8us; 6us; 14us; 0us; 16390us; 1us; 32768us; 1us; 11us; 0us; 16391us; 1us; 32768us; 5us; 13us; 0us; 16392us; 5us; 32768us; 0us; 2us; 1us; 3us; 2us; 4us; 4us; 8us; 6us; 14us; 0us; 16393us; |]
let _fsyacc_actionTableRowOffsets = [|0us; 6us; 7us; 8us; 9us; 10us; 12us; 13us; 14us; 20us; 21us; 23us; 24us; 26us; 27us; 33us; |]
let _fsyacc_reductionSymbolCounts = [|1us; 1us; 1us; 1us; 2us; 1us; 2us; 2us; 2us; 2us; |]
let _fsyacc_productionToNonTerminalTable = [|0us; 1us; 1us; 1us; 1us; 1us; 2us; 3us; 4us; 5us; |]
let _fsyacc_immediateActions = [|65535us; 49152us; 16385us; 16386us; 16387us; 65535us; 16388us; 16389us; 65535us; 16390us; 65535us; 16391us; 65535us; 16392us; 65535us; 16393us; |]
let _fsyacc_reductions ()  =    [| 
# 124 "asdf.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'a)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
                      raise (Microsoft.FSharp.Text.Parsing.Accept(Microsoft.FSharp.Core.Operators.box _1))
                   )
                 : '_startSqlExpression));
# 133 "asdf.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 27 "asdf.fsy"
                                                 let aaa=_1  in (fun s -> LocalVar(s)) aaa
                   )
# 27 "asdf.fsy"
                 : 'a));
# 144 "asdf.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 28 "asdf.fsy"
                                               let aab=_1  in (fun s -> Ident(s)) aab
                   )
# 28 "asdf.fsy"
                 : 'a));
# 155 "asdf.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 29 "asdf.fsy"
                                                   let aac=_1  in (fun s -> GlobalVar(s)) aac
                   )
# 29 "asdf.fsy"
                 : 'a));
# 166 "asdf.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'yard_exp_brackets_1)) in
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 30 "asdf.fsy"
                                                                    let aae=_1  in aae
                   )
# 30 "asdf.fsy"
                 : 'a));
# 178 "asdf.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'yard_exp_brackets_2)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 32 "asdf.fsy"
                                         let aaf=_1  in (fun (e, where) -> Select(e, Ident(where))) aaf
                   )
# 32 "asdf.fsy"
                 : 'a));
# 189 "asdf.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'a)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 34 "asdf.fsy"
                                                                   let aad=_2  in aad
                   )
# 34 "asdf.fsy"
                 : 'yard_exp_brackets_1));
# 201 "asdf.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'yard_exp_brackets_3)) in
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 37 "asdf.fsy"
                                               let aai=_1  in let aaj=_2  in (aai,aaj)
                   )
# 37 "asdf.fsy"
                 : 'yard_exp_brackets_2));
# 213 "asdf.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : 'yard_exp_brackets_4)) in
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 39 "asdf.fsy"
                                                                          let aah=_1  in aah
                   )
# 39 "asdf.fsy"
                 : 'yard_exp_brackets_3));
# 225 "asdf.fs"
        (fun (parseState : Microsoft.FSharp.Text.Parsing.IParseState) ->
            let _1 = (let data = parseState.GetInput(1) in (Microsoft.FSharp.Core.Operators.unbox data : string)) in
            let _2 = (let data = parseState.GetInput(2) in (Microsoft.FSharp.Core.Operators.unbox data : 'a)) in
            Microsoft.FSharp.Core.Operators.box
                (
                   (
# 41 "asdf.fsy"
                                                                      let aag=_2  in aag
                   )
# 41 "asdf.fsy"
                 : 'yard_exp_brackets_4));
|]
# 238 "asdf.fs"
let tables () : Microsoft.FSharp.Text.Parsing.Tables<_> = 
  { reductions= _fsyacc_reductions ();
    endOfInputTag = _fsyacc_endOfInputTag;
    tagOfToken = tagOfToken;
    dataOfToken = _fsyacc_dataOfToken; 
    actionTableElements = _fsyacc_actionTableElements;
    actionTableRowOffsets = _fsyacc_actionTableRowOffsets;
    stateToProdIdxsTableElements = _fsyacc_stateToProdIdxsTableElements;
    stateToProdIdxsTableRowOffsets = _fsyacc_stateToProdIdxsTableRowOffsets;
    reductionSymbolCounts = _fsyacc_reductionSymbolCounts;
    immediateActions = _fsyacc_immediateActions;
    gotos = _fsyacc_gotos;
    sparseGotoTableRowOffsets = _fsyacc_sparseGotoTableRowOffsets;
    tagOfErrorTerminal = _fsyacc_tagOfErrorTerminal;
    parseError = (fun (ctxt:Microsoft.FSharp.Text.Parsing.ParseErrorContext<_>) -> 
                              match parse_error_rich with 
                              | Some f -> f ctxt
                              | None -> parse_error ctxt.Message);
    numTerminals = 10;
    productionToNonTerminalTable = _fsyacc_productionToNonTerminalTable  }
let engine lexer lexbuf startState = (tables ()).Interpret(lexer, lexbuf, startState)
let SqlExpression lexer lexbuf : 'a =
    Microsoft.FSharp.Core.Operators.unbox ((tables ()).Interpret(lexer, lexbuf, 0))
